version: "2.4"

services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
  apirest_beers:
    image: yethro/apirest_beers:latest
    build:
      context: .
    depends_on:
      - 'mongo'
    ports:
      - '8081:8081'
    environment:
      - SECRET_KEY_BASE=secret
      - MONGO_URL=mongodb://mongo:27017/apirest_beers
volumes:
  mongo:
